### ISSUE TITLE
The Subpasses example caused system hang

### ISSUE THREAD

**Issue by masahi** [GPUOpen-LibrariesAndSDKs/V-EZ#33]
As in the title. I'm on Ubuntu 16.04 with R9 Nano. My driver is AMDVLK open source driver.

**Comment by WebFreak001** [comment]
I'm experiencing a segmentation fault with Subpasses example:

```
Thread 1 "Subpasses" received signal SIGSEGV, Segmentation fault.
0x00007fffeb0c0256 in ?? () from /usr/lib/libvulkan_radeon.so
(gdb) bt
#0  0x00007fffeb0c0256 in ?? () from /usr/lib/libvulkan_radeon.so
#1  0x00007fffeb0c0835 in ?? () from /usr/lib/libvulkan_radeon.so
#2  0x00007fffeb0c1e74 in ?? () from /usr/lib/libvulkan_radeon.so
#3  0x00007fffe9f0a97e in ?? () from /usr/lib/libVkLayer_core_validation.so
#4  0x00007fffe9c6a503 in ?? () from /usr/lib/libVkLayer_object_tracker.so
#5  0x00007fffe9995ee8 in ?? () from /usr/lib/libVkLayer_parameter_validation.so
#6  0x00007fffe97176aa in ?? () from /usr/lib/libVkLayer_threading.so
#7  0x00007ffff787e02b in vez::StreamDecoder::CmdNextSubpass(vez::CommandBuffer&, vez::MemoryStream&) ()
   from /home/webfreak/dev/V-EZ/Bin/x86_64/libVEZ.so
#8  0x00007ffff787dfc0 in vez::StreamDecoder::Decode(vez::CommandBuffer&, vez::StreamEncoder&) ()
   from /home/webfreak/dev/V-EZ/Bin/x86_64/libVEZ.so
#9  0x00007ffff7808640 in vez::CommandBuffer::End() () from /home/webfreak/dev/V-EZ/Bin/x86_64/libVEZ.so
#10 0x00007ffff78ccc69 in vezEndCommandBuffer () from /home/webfreak/dev/V-EZ/Bin/x86_64/libVEZ.so
#11 0x0000555555585690 in Subpasses::CreateCommandBuffer() ()
#12 0x00005555555832e0 in Subpasses::Initialize() ()
#13 0x0000555555560dc5 in AppBase::Run() ()
#14 0x0000555555568c99 in main ()
```

on ArchLinux with RX 480, vulkan-radeon-git, amdvlk-git, llvm-svn, mesa-git

If I remove vulkan-radeon I get a system hang (just the graphics stack actually, sound still works and it seems to be processing stuff) too
